name: Auto-merge PRs from private fork into public repo

# Trigger on new issue comments
on:
  issue_comment:
    types: [created]

jobs:
  merge_pr:
    # Run only if:
    # - The comment is on a PR (not a regular issue)
    # - The comment text is exactly 'merge', 'Merge', or 'MERGE'
    # - The comment author is the pre-defined maintainer
    if: >
      github.event.issue.pull_request != null &&
      (github.event.comment.body == 'merge' || github.event.comment.body == 'MERGE' || github.event.comment.body == 'Merge') &&
      github.event.comment.user.login == 'arianabuilds'
    runs-on: ubuntu-latest
    steps:
      - name: Debug Variables and Remote URL
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "PR head ref: ${{ github.event.issue.pull_request.head.ref }}"
          echo "PR number: ${{ github.event.issue.number }}"
          echo "Comment Body: ${{ github.event.comment.body }}"
          echo "Comment User Login: ${{ github.event.comment.user.login }}"
          # Check that our tokens are set (masked output)
          if [ -z "${{ secrets.UPSTREAM_REPO_TOKEN }}" ]; then echo "UPSTREAM_REPO_TOKEN is NOT set"; else echo "UPSTREAM_REPO_TOKEN is set"; fi
          if [ -z "${{ secrets.PRIVATE_REPO_TOKEN }}" ]; then echo "PRIVATE_REPO_TOKEN is NOT set"; else echo "PRIVATE_REPO_TOKEN is set"; fi
          # Construct the remote URL (masking the token in the echo)
          REMOTE_URL="https://x-access-token:***@github.com/${{ github.repository }}.git"
          echo "Constructed remote URL: ${REMOTE_URL}"
          # Test remote access with ls-remote
          git ls-remote "https://x-access-token:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/${{ github.repository }}.git"

      - name: 1. Checkout Public Upstream Repository
        uses: actions/checkout@v3
        with:
          repository: arianabuilds/blowjobchain-web
          token: ${{ secrets.UPSTREAM_REPO_TOKEN }}
          fetch-depth: 0 # Fetch full history to allow merging

      - name: 2. Add Private Fork as Remote
        run: git remote add pato "https://x-access-token:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/${{ github.repository }}.git"

      - name: 3. Fetch only the PR branch from private fork
        run: |
          pr_number="${{ github.event.issue.number }}"
          # Fetch only the pull request branch (avoiding a full fetch of all refs)
          git fetch pato "refs/pull/${pr_number}/head:temp_pr"

      - name: 4. Checkout main branch of upstream repository
        run: git checkout main

      - name: 5. Merge PR branch into main
        run: |
          pr_number="${{ github.event.issue.number }}"
          git merge temp_pr -m "Merge pull request pato/${pr_number}"

      - name: 6. Push updated main branch back to public repository
        run: git push origin main
