name: Auto-merge PRs from private fork into public repo

# Trigger on new issue comments
on:
  issue_comment:
    types: [created]

jobs:
  merge_pr:
    # Run only if:
    # - The comment is on a PR (not a regular issue)
    # - The comment text is exactly "merge" (case-insensitive)
    # - The comment author is the pre-defined maintainer
    if: >
      github.event.issue.pull_request != null &&
      (github.event.comment.body == 'merge' || github.event.comment.body == 'MERGE' || github.event.comment.body == 'Merge') &&
      github.event.comment.user.login == 'arianabuilds'
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Public Upstream Repository
        uses: actions/checkout@v3
        with:
          repository: arianabuilds/blowjobchain
          token: ${{ secrets.UPSTREAM_REPO_TOKEN }}
          fetch-depth: 0 # Fetch full history to allow merging

      - name: 2. Add Private Fork as a Remote
        run: git remote add pato "https://github.com/${{ github.repository }}.git" # Env var provided by where this action is run

      - name: 3. Fetch branches from private fork
        run: git fetch pato

      - name: 4. Checkout main branch of upstream repository
        run: git checkout main

      - name: 5. Merge PR branch from private fork into main (using PR event data)
        run: |
          pr_branch="${{ github.event.issue.pull_request.head.ref }}"
          git merge pato/${pr_branch} -m "Merge pull request #${pr_number} from pato/${pr_branch}"

      - name: 6. Push updated main branch back to public repository
        run: git push origin main
